const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('report-studio.html','utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const elements={};
function element(){return {value:'',textContent:'',children:[],className:'',replaceChildren(...c){this.children=c},append(...c){this.children.push(...c)},addEventListener(){},focus(){},select(){},click(){}}}
const context={document:{getElementById(id){return elements[id]??=element()},createElement:element,createTextNode:s=>s},window:{addEventListener(){}},URL,Blob,AbortController,setTimeout,clearTimeout,console,confirm:()=>true,navigator:{clipboard:{writeText:async()=>{}}},fetch:async()=>({ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify({revised_report:'No effusion.',issues:[{category:'Laterality',detail:'Check side.'}],changes:['Corrected spelling.']})}}]})})};
vm.createContext(context);vm.runInContext(script,context);
vm.runInContext(`validate(JSON.parse(${JSON.stringify(fs.readFileSync('report-studio-settings.json','utf8').replace(/^\uFEFF/,''))}))`,context);
assert.throws(()=>vm.runInContext(`validateURL('http://external.example/v1')`,context));
assert.throws(()=>vm.runInContext(`parseReview('{"revised_report":"x","issues":["bad"],"changes":[]}')`,context));
elements.endpoint.value='https://api.openai.com/v1/chat/completions';elements.key.value='mock';elements.model.value='mock-model';elements.source.value='No effusoin.';elements.language.value='Same as original';
(async()=>{await elements.review.onclick();assert.equal(elements.revision.value,'No effusion.');assert.equal(elements.review.disabled,false);assert.equal(elements.cancel.disabled,true);assert.equal(elements.issues.children[0].children[0].textContent,'Laterality');context.fetch=async()=>({ok:false,status:401});await elements.review.onclick();assert.match(elements.status.textContent,/401/);assert.match(elements.context.textContent,/Previous draft/);context.fetch=async()=>({ok:true,json:async()=>({choices:[{message:{content:'bad json'}}]})});await elements.review.onclick();assert.equal(elements.revision.value,'');assert.equal(elements.raw.textContent,'bad json');elements.templateName.value='Custom';elements.templateBody.value='Findings:';elements.update.onclick();assert.equal(vm.runInContext('templates[0].name',context),'Custom');elements.load.files=[{size:20,text:async()=>'{"version":9}'}];await elements.load.onchange({target:elements.load});assert.match(elements.status.textContent,/Invalid settings/);console.log('PASS: settings validation, endpoint validation, structured response, review success, API failure, malformed response, template update, invalid import.');})();
